api_platform:
    # The title of the API.
    title: 'EresNote REST API Documentation'

    # The description of the API.
    description: 'For comprehension and trying out.'

    # The version of the API.
    version: '1.0.0'

    mapping:
        paths:
          - '%kernel.project_dir%/src/Entity'
          - '%kernel.project_dir%/config/api_platform'



