App\Entity\User:
    properties:
        email:
            - Email:
                message: 'user.email.not_valid'
        plainPassword:
            - NotBlank:
                message: 'user.password.not_blank'
            - Length:
                min: 6
                minMessage: 'user.password.min_length'