#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#register:
#    path: /register
#    controller: App\Controller\AuthController::register
#    methods: POST

guest:
  path: /guest/register
  controller: App\Controller\AuthController::register

willkommen:
  path: /api/willkommen
  controller: App\Controller\AuthController::testLogin



api_login_check:
    path: /api/login_check

