# api/config/api_platform/resources.yaml
resources:
    App\Entity\User:
      collectionOperations:
        get: ~
      itemOperations:
        get: ~
    App\Entity\Note:
        shortName: 'Note'                   # optional
        description: 'Saved notes of the user.' # optional
        #iri: 'http://schema.org/Offer'       # optional
        attributes:                          # optional
            pagination_items_per_page: 25    # optional